data_pack:
    load: .
    min_format: [111,0]
		max_format: [121,0]
    zipped: true

resource_pack:
    load: .
    min_format: [69,0]
    max_format: [97.1,0]
    zipped: true

require:
  - src.plugins.generate.load_hats

pipeline:
  - src.plugins.generate
  - mecha

output: .build

"description": [
    {"text":"Villager hats now at your door!"}
]