data_pack:
    load: .
    min_format: [88,1]
    max_format: [107,1]
    zipped: true

resource_pack:
    load: .
    min_format: [69,0]
    max_format: [88,0]
    zipped: true

require:
  - src.plugins.generate.load_hats

pipeline:
  - src.plugins.generate
  - mecha

output: .build

"description": [
    {"text":"Villager hats now at your door!"}
]