data_pack:
    load: .
    min_format: [94,1]
    max_format: [107,1]
    zipped: true

resource_pack:
    load: .
    min_format: [75,0]
    max_format: [88,0]
    zipped: true

require:
  - src.plugins.generate.load_hats

pipeline:
  - src.plugins.generate
  - mecha

output: .build

"description": [
    {"text":"With Villager Vanity, you can dress like any villager you desire! (well only their hats)"}
]